---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aap-mcp-config
  labels:
    app: aap-mcp
data:
  BASE_URL: "http://localhost:8000"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aap-api-categories
  labels:
    app: aap-mcp
data:
  aap-mcp.yaml: |
    ---
    # Configuration for API query recording
    record_api_queries: true

    # Configuration for HTTPS certificate validation
    ignore-certificate-errors: true

    categories:
      job_management:
        - controller.job_templates_launch_create
        - controller.workflow_job_templates_launch_create
        - controller.jobs_read
        - controller.workflow_jobs_read
        - controller.jobs_stdout_read
        - controller.jobs_job_events_list
        - controller.jobs_cancel_create
        - controller.workflow_jobs_cancel_create
        - controller.jobs_relaunch_create     
        - controller.jobs_list
        - eda.activation_instances_list
        - eda.activation_instances_logs_list
        - controller.analytics_list
        - controller.metrics_list
        - controller.projects_list
        - controller.job_templates_list

      inventory_management:
        - controller.inventories_list
        - controller.inventory_sources_update_create
        - controller.hosts_list
        - controller.hosts_read
        - controller.hosts_variable_data_read
        - controller.groups_list
        - controller.groups_create
        # controller: /api/v2/hosts/{id}/insights/
        # controller: /api/v2/settings/database/

      system_monitoring:
        - controller.ping_list
        - controller.config_list
        - controller.instance_groups_list
        - controller.instance_groups_create
        - controller.mesh_visualizer_list
        - controller.instances_create
        - gateway.activitystream_list
        - gateway.authenticators_list
        - gateway.http_ports_list
        - gateway.http_ports_create  
        # controller: /api/v2/instance_groups/{id}/capacity/
        - controller.activity_stream_list
        - controller.instances_read
        - gateway.feature_flags_state_retrieve


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aap-mcp-logs-pvc
  labels:
    app: aap-mcp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: aap-mcp
  labels:
    app: aap-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aap-mcp
  template:
    metadata:
      labels:
        app: aap-mcp
    spec:
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: aap-mcp-logs-pvc
        - name: aap-mcp-yaml
          configMap:
            name: aap-api-categories
      containers:
        - name: aap-mcp
          image: quay.io/jameswong/mcp-poc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: PORT
              value: '3000'
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: aap-mcp-config
                  key: BASE_URL

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
            - name: aap-mcp-yaml
              mountPath: /app/aap-mcp.yaml
              subPath: aap-mcp.yaml
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: aap-mcp
  labels:
    app: aap-mcp
spec:
  selector:
    app: aap-mcp
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: aap-mcp
  labels:
    app: aap-mcp
spec:
  to:
    kind: Service
    name: aap-mcp
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
